export enum ApiErrorCode {
  // Generic HTTP errors (mapped from HttpStatus)
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Auth specific errors
  INVALID_AUTH_HEADER = 'INVALID_AUTH_HEADER',
  TOKEN_MISSING = 'TOKEN_MISSING',
  INVALID_TOKEN = 'INVALID_TOKEN',
  AUTH_VERIFICATION_FAILED = 'AUTH_VERIFICATION_FAILED',
  USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED',
  SUPABASE_AUTH_REGISTER_ERROR = 'SUPABASE_AUTH_REGISTER_ERROR',
  SUPABASE_AUTH_LOGIN_ERROR = 'SUPABASE_AUTH_LOGIN_ERROR',
  AUTH_REGISTER_FAILED = 'AUTH_REGISTER_FAILED',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',

  // User specific errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  USER_CREATION_FAILED = 'USER_CREATION_FAILED',
  USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
  USER_DELETION_FAILED = 'USER_DELETION_FAILED',
  FETCH_USERS_FAILED = 'FETCH_USERS_FAILED',

  // Permission/Authorization errors
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  // Add more as your application grows...
}
